# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residencial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifa',
            name='comercial_cargo_fijo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarifa',
            name='residencial_cargo_fijo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
            preserve_default=False,
        ),
    ]
