# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residencial', '0003_auto_20170706_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifa',
            name='anio',
            field=models.CharField(default=2017, max_length=10),
            preserve_default=False,
        ),
    ]
