# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 04:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residencial', '0004_tarifa_anio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarifa',
            old_name='anio',
            new_name='año',
        ),
    ]
