# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 04:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residencial', '0005_auto_20170706_0449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarifa',
            old_name='año',
            new_name='anio',
        ),
    ]
