# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-13 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residencial', '0010_auto_20171012_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('utilidad', models.DecimalField(decimal_places=2, max_digits=4)),
                ('indirectos', models.DecimalField(decimal_places=2, max_digits=4)),
                ('potencia_panel', models.DecimalField(decimal_places=0, max_digits=4)),
            ],
        ),
    ]
