# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-13 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residencial', '0011_configuracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='IVA',
            field=models.DecimalField(decimal_places=2, default=0.16, max_digits=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='indirectos',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='utilidad',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
