# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-16 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residencial', '0014_auto_20171013_0247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('potencia_panel', models.DecimalField(decimal_places=0, max_digits=4)),
                ('longitud_del_string', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
            options={
                'verbose_name_plural': 'Configuracion fotovoltaica',
            },
        ),
        migrations.AlterModelOptions(
            name='configuracion',
            options={'verbose_name_plural': 'Configuracion economica'},
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='potencia_panel',
        ),
    ]
