# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-16 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residencial', '0015_auto_20171016_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion2',
            name='distancia_maxima_de_triangles',
            field=models.DecimalField(decimal_places=1, default=2.0, max_digits=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='configuracion2',
            name='longitud_del_string',
            field=models.DecimalField(decimal_places=0, max_digits=1),
        ),
    ]
