# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-16 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residencial', '0016_auto_20171016_0154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuracion2',
            old_name='distancia_maxima_de_triangles',
            new_name='distancia_maxima_entre_triangulos',
        ),
        migrations.AlterField(
            model_name='configuracion2',
            name='longitud_del_string',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
