# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-22 01:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residencial', '0017_auto_20171016_1301'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EquipoGenerador',
            new_name='Inversor',
        ),
        migrations.RenameField(
            model_name='inversor',
            old_name='potencia',
            new_name='potencia_pico',
        ),
    ]
