# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-22 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residencial', '0018_auto_20171022_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inversor',
            name='potencia_pico',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
