# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-29 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residencial', '0019_auto_20171022_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='inversor',
            name='costo_de_instalacion',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=8),
            preserve_default=False,
        ),
    ]
