# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-07 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residencial', '0020_inversor_costo_de_instalacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='tipo_cambio',
            field=models.DecimalField(decimal_places=2, default=18.5, max_digits=4),
            preserve_default=False,
        ),
    ]
